version: "3"
services:
  api:
    build: ./api
    command: run
    links:
      - db
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - ENV=local
      - DB_URL=postgresql://postgres@db/c10y
      # Force the Python stdout and stderr streams to be unbuffered
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount python and HTML source code to minimize need for re-building during development
      - ./api/c10y:/home/c10y/c10y
      - ./api/www:/home/c10y/www

  # Replaced by a dedicated database server in production (e.g. AWS RDS)
  db:
    image: postgres:14.8
    environment:
      - POSTGRES_DB=c10y
      # For development, if you can reach the database host you can connect to it. Only the
      # 'api' container should be able to reach this db over the default bridge network.
      # Replaced by a secure username and password in production.
      - POSTGRES_HOST_AUTH_METHOD=trust
